---
- name: Create jenkins directories
  file:
    path: "{{ jenkins_deploy_dir }}"
    state: directory
    owner: "1000"
    group: "1000"
  become: true

- name: Render jenkins docker-compose file
  template:
    src: docker-compose.yml
    dest: "{{ jenkins_deploy_dir }}/docker-compose.yml"
    owner: "{{ default_user }}"
    group: "{{ default_user }}"
  become: true

